<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DevSecApi.Domain\DevSecApi.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Services\Abstractions\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AngleSharp" Version="1.8.2" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
  </ItemGroup>

</Project>
